apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  type: NodePort
  ports:
    - name: blog80
      port: 8088
      targetPort: 80
      nodePort: 30008
  selector:
    app: blog
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: blog
spec:
  selector:
    matchLabels:
      app: blog
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - image: thisisgjf/blog
          name: blog
          ports:
            - containerPort: 80
              name: blog80
