server:
  port: 80
spring:
  resources:
    static-locations: file:static/html/
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /**
  http:
    encoding:
      charset: UTF-8
      force: true


io:
  gjf:
    gitpath: rep/Think
    nginxpath: static/html/
    giturl: https://github.com/GuoJiafeng/Think.git






