server:
  port: 1211
  servlet:
    context-path: /Blog
spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  http:
    encoding:
      charset: UTF-8
      force: true


io:
  gjf:
    gitpath: git@github.com:GuoJiafeng/ProblemRepository.git
    nginxpath: /usr/share/nginx/html/
    giturl: /root/ProblemRepository/
    imagepath: /root/ProblemRepository/assets






