server:
  port: 1211
  servlet:
    context-path: /Blog
spring:
  resources:
    static-locations: file:./html
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /**
  http:
    encoding:
      charset: UTF-8
      force: true


io:
  gjf:
    gitpath: ~/Think/
    nginxpath: /usr/share/nginx/html/
    giturl: https://github.com/GuoJiafeng/Think.git






